import type { Struggle, Goal, Action } from '@/types';

const ACTION_BANK: Record<string, Omit<Action, 'id' | 'completed'>[]> = {
  'procrastination+work': [
    {
      icon: 'time-outline',
      title: 'Start work for 2 minutes',
      titleAr: 'ابدأ شغل لمدة دقيقتين بس',
      description: 'The 2-minute rule lowers the barrier to entry. Just start.',
      descriptionAr: 'قاعدة الدقيقتين بتكسر حاجز الكسل. ابدأ بس.',
      duration: '2m',
    },
    {
      icon: 'list-outline',
      title: 'Write 3 tasks for tomorrow',
      titleAr: 'اكتب ٣ مهام لبكرة',
      description: 'Planning tonight reduces tomorrow\'s decision fatigue.',
      descriptionAr: 'لو خططت بالليل هتوفر على نفسك فرهدة التفكير بكرة.',
      duration: '5m',
    },
    {
      icon: 'ban-outline',
      title: 'No social media before noon',
      titleAr: 'مفيش سوشيال ميديا قبل الظهر',
      description: 'Protect your early morning dopamine levels.',
      descriptionAr: 'احمي تركيزك ومستويات الدوبامين في أول اليوم.',
      duration: '4h',
    },
  ],
  'procrastination+study': [
    {
      icon: 'book-outline',
      title: 'Study for 25 min focused',
      titleAr: 'ذاكر ٢٥ دقيقة بتركيز',
      description: 'Use the Pomodoro technique to build study momentum.',
      descriptionAr: 'استخدم البومودورو عشان تبني زخم المذاكرة.',
      duration: '25m',
    },
    {
      icon: 'pencil-outline',
      title: 'Summarize one chapter',
      titleAr: 'لخص فصل واحد',
      description: 'Active recall helps embed new knowledge.',
      descriptionAr: 'التلخيص بيثبت المعلومات الجديدة في دماغك.',
      duration: '15m',
    },
    {
      icon: 'phone-portrait-outline',
      title: 'No phone during study',
      titleAr: 'الموبايل برا الأوضة وقت المذاكرة',
      description: 'Out of sight, out of mind. Boost concentration.',
      descriptionAr: 'بعيد عن العين بعيد عن التشتيت. ركز أكتر.',
      duration: '30m',
    },
  ],
  'procrastination+health': [
    {
      icon: 'walk-outline',
      title: '15 min walk outside',
      titleAr: 'انزل اتمشى ١٥ دقيقة',
      description: 'Getting light and movement breaks mental loops.',
      descriptionAr: 'الهوا والحركة بيفكوا الدماغ ويجددوا نشاطك.',
      duration: '15m',
    },
    {
      icon: 'water-outline',
      title: 'Drink 2L water today',
      titleAr: 'اشرب ٢ لتر ماية النهاردة',
      description: 'Hydration improves brain performance and energy.',
      descriptionAr: 'الماية بتحسن أداء مخك وطاقتك بشكل عام.',
      duration: '1d',
    },
    {
      icon: 'bed-outline',
      title: 'Sleep before midnight',
      titleAr: 'نام قبل نص الليل',
      description: 'Fix your sleep window to regulate morning energy.',
      descriptionAr: 'اظبط نومك عشان تصحى فايق الصبح.',
      duration: '8h',
    },
  ],
  'procrastination+life_balance': [
    {
      icon: 'phone-portrait-outline',
      title: 'Put phone away for 30 minutes',
      titleAr: 'ابعد عن الموبايل ٣٠ دقيقة',
      description: 'Physical distance from your device creates mental space.',
      descriptionAr: 'لما تبعد الموبايل هترتاح نفسياً وتصفي ذهنك.',
      duration: '30m',
    },
    {
      icon: 'sparkles-outline',
      title: 'Clean one area of your space',
      titleAr: 'روق حتة صغيرة في أوضتك',
      description: 'External order translates to internal clarity.',
      descriptionAr: 'المكان المترتب بيخلي دماغك مترتبة.',
      duration: '10m',
    },
    {
      icon: 'partly-sunny-outline',
      title: 'Plan tomorrow before sleep',
      titleAr: 'خطط لبكرة قبل ما تنام',
      description: 'Offload tomorrow\'s decisions tonight for better rest.',
      descriptionAr: 'وفر قرارات بكرة بالليل عشان تنام مرتاح.',
      duration: '5m',
    },
  ],
  'phone_addiction+work': [
    {
      icon: 'phone-portrait-outline',
      title: 'Phone off for 2 hours at work',
      titleAr: 'اقفل الموبايل ساعتين في الشغل',
      description: 'Deep focus block to finish high-priority tasks.',
      descriptionAr: 'وقت تركيز عميق عشان تخلص أهم حاجة وراك.',
      duration: '2h',
    },
    {
      icon: 'alarm-outline',
      title: 'Set app time limits',
      titleAr: 'اعمل ليمت لتطبيقات السوشيال',
      description: 'Hard limits reduce mindless scrolling.',
      descriptionAr: 'حدود صارمة عشان تبطل سكرولينج عالفاضي.',
      duration: '10m',
    },
    {
      icon: 'list-outline',
      title: 'Finish hardest task first',
      titleAr: 'خلص أصعب مهمة في الأول',
      description: 'Eat the frog to gain confidence early.',
      descriptionAr: 'كل الضفدع الأول عشان تخلص وتاخد ثقة.',
      duration: '45m',
    },
  ],
  'phone_addiction+study': [
    {
      icon: 'phone-portrait-outline',
      title: 'Phone in another room while studying',
      titleAr: 'الموبايل في أوضة تانية وقت المذاكرة',
      description: 'Drastically reduce temptation and screen wakeups.',
      descriptionAr: 'عشان تقلل إغراء إنك تفتح الشاشة كل شوية.',
      duration: '1h',
    },
    {
      icon: 'book-outline',
      title: 'Read 20 pages',
      titleAr: 'اقرأ ٢٠ صفحة',
      description: 'Build single-focus cognitive stamina.',
      descriptionAr: 'ابني قدرتك إنك تركز في حاجة واحدة بس.',
      duration: '30m',
    },
    {
      icon: 'checkmark-circle-outline',
      title: 'Complete one assignment',
      titleAr: 'خلص تكليف واحد',
      description: 'Focus solely on completion, ignore perfection.',
      descriptionAr: 'ركز بس إنك تخلص، بلاش تدور على المثالية.',
      duration: '45m',
    },
  ],
  'phone_addiction+health': [
    {
      icon: 'phone-portrait-outline',
      title: 'No phone 1 hour before bed',
      titleAr: 'مفيش موبايل قبل النوم بساعة',
      description: 'Melatonin production is disrupted by blue light.',
      descriptionAr: 'الضوء الأزرق بيبوظ إفراز هرمون النوم.',
      duration: '1h',
    },
    {
      icon: 'walk-outline',
      title: '20 min exercise',
      titleAr: 'اتمرن ٢٠ دقيقة',
      description: 'Elevate your heart rate to boost overall metabolism.',
      descriptionAr: 'عرق شوية عشان ترفع معدل حرق جسمك.',
      duration: '20m',
    },
    {
      icon: 'nutrition-outline',
      title: 'Eat one healthy meal',
      titleAr: 'كل وجبة صحية واحدة',
      description: 'Fuel your system with whole foods.',
      descriptionAr: 'غذي جسمك بأكل مفيد بجد.',
      duration: '20m',
    },
  ],
  'phone_addiction+life_balance': [
    {
      icon: 'phone-portrait-outline',
      title: 'Delete one distracting app',
      titleAr: 'امسح أكتر تطبيق بيضيع وقتك',
      description: 'Break the habit loop of automatic tapping.',
      descriptionAr: 'اكسر عادة إنك تفتح التطبيق بدون وعي.',
      duration: '2m',
    },
    {
      icon: 'people-outline',
      title: 'Spend 30 min with family',
      titleAr: 'اقعد ٣٠ دقيقة مع عيلتك',
      description: 'Be fully present without digital distractions.',
      descriptionAr: 'خليك حاضر معاهم بجد من غير موبايل.',
      duration: '30m',
    },
    {
      icon: 'leaf-outline',
      title: 'Go outside for 20 min',
      titleAr: 'انزل اتمشى في الهوا ٢٠ دقيقة',
      description: 'Ground yourself in nature and fresh air.',
      descriptionAr: 'شم هوا نضيف وافصل شوية عن التكنولوجيا.',
      duration: '20m',
    },
  ],
  'focus+work': [
    {
      icon: 'locate-outline',
      title: 'Deep work for 45 min',
      titleAr: 'شغل بتركيز عميق ٤٥ دقيقة',
      description: 'Zero notifications, single tab, pure output.',
      descriptionAr: 'مفيش إشعارات، تابة واحدة مفتوحة، وإنتاج وبس.',
      duration: '45m',
    },
    {
      icon: 'document-text-outline',
      title: 'Plan your top 3 priorities',
      titleAr: 'حدد أهم ٣ أولويات ليك',
      description: 'Write them down before checking emails.',
      descriptionAr: 'اكتبهم في ورقة قبل ما تفتح الإيميلات.',
      duration: '10m',
    },
    {
      icon: 'notifications-off-outline',
      title: 'Turn off all notifications',
      titleAr: 'اقفل كل الإشعارات',
      description: 'Eliminate interruptions that break thought trains.',
      descriptionAr: 'امنع أي حاجة تفصل حبل أفكارك.',
      duration: '5m',
    },
  ],
  'focus+study': [
    {
      icon: 'locate-outline',
      title: 'Study one topic deeply',
      titleAr: 'ذاكر موضوع واحد بتركيز',
      description: 'Immerse in the material without context switching.',
      descriptionAr: 'اغطس في الموضوع من غير ما تشتت نفسك.',
      duration: '50m',
    },
    {
      icon: 'document-text-outline',
      title: 'Take handwritten notes',
      titleAr: 'اكتب نوتس بإيدك',
      description: 'Writing by hand forces cognitive synthesis.',
      descriptionAr: 'الكتابة بالإيد بتجبر مخك إنه يركز ويلخص.',
      duration: '20m',
    },
    {
      icon: 'notifications-off-outline',
      title: 'Study in a quiet place',
      titleAr: 'ذاكر في مكان هادي',
      description: 'Silence is essential for complex abstract thoughts.',
      descriptionAr: 'الهدوء مهم جداً عشان تفهم الأفكار المعقدة.',
      duration: '1h',
    },
  ],
  'focus+health': [
    {
      icon: 'body-outline',
      title: '10 min meditation',
      titleAr: '١٠ دقايق تأمل',
      description: 'Train attention control and calm stress systems.',
      descriptionAr: 'مرن تركيزك وهدي جهازك العصبي.',
      duration: '10m',
    },
    {
      icon: 'barbell-outline',
      title: 'One focused workout',
      titleAr: 'تمرين واحد بتركيز',
      description: 'Mind-muscle connection during lift or run.',
      descriptionAr: 'ركز في العضلة اللي بتلعبها وأنت بتتمرن.',
      duration: '45m',
    },
    {
      icon: 'moon-outline',
      title: '7+ hours sleep',
      titleAr: 'نام أكتر من ٧ ساعات',
      description: 'Sleep cycles restore executive function.',
      descriptionAr: 'النوم الكفاية بيرجع لمخك قدرته على التركيز.',
      duration: '8h',
    },
  ],
  'focus+life_balance': [
    {
      icon: 'book-outline',
      title: 'Read for 20 min',
      titleAr: 'اقرأ لمدة ٢٠ دقيقة',
      description: 'Non-screen reading calms down cognitive load.',
      descriptionAr: 'القراءة في كتاب بتهدي دماغك وتفصلك عن الشاشات.',
      duration: '20m',
    },
    {
      icon: 'body-outline',
      title: '5 min breathing exercise',
      titleAr: '٥ دقايق تنفس بعمق',
      description: 'Box breathing resets autonomic nervous system.',
      descriptionAr: 'تمارين التنفس بتعمل ريستارت لجهازك العصبي.',
      duration: '5m',
    },
    {
      icon: 'phone-portrait-outline',
      title: 'No screens after 9 PM',
      titleAr: 'مفيش شاشات بعد ٩ بالليل',
      description: 'Disconnect early to let the mind wind down.',
      descriptionAr: 'افصل بدري عشان تدي فرصة لدماغك ترتاح.',
      duration: '2h',
    },
  ],
  'discipline+work': [
    {
      icon: 'alarm-outline',
      title: 'Wake up at fixed time',
      titleAr: 'اصحى في ميعاد ثابت',
      description: 'Circadian stability yields reliable energy.',
      descriptionAr: 'ثبات ميعاد الصحيان هيديك طاقة مضمونة طول اليوم.',
      duration: '5m',
    },
    {
      icon: 'checkmark-circle-outline',
      title: 'Finish what you start',
      titleAr: 'خلص اللي تبدأه',
      description: 'Say no to new tasks until this one is done.',
      descriptionAr: 'قول لا لأي حاجة جديدة لحد ما تخلص اللي في إيدك.',
      duration: '1h',
    },
    {
      icon: 'list-outline',
      title: 'Follow your schedule',
      titleAr: 'امشي على جدولك',
      description: 'Actions match intentions, regardless of mood.',
      descriptionAr: 'نفذ اللي نويته بغض النظر عن مزاجك.',
      duration: '4h',
    },
  ],
  'discipline+study': [
    {
      icon: 'alarm-outline',
      title: 'Study at the same time daily',
      titleAr: 'ذاكر في نفس الميعاد كل يوم',
      description: 'Habituate studying to remove motivational resistance.',
      descriptionAr: 'خلي المذاكرة عادة عشان تلغي مقاومة الكسل.',
      duration: '1h',
    },
    {
      icon: 'book-outline',
      title: 'Review notes before bed',
      titleAr: 'راجع النوتس قبل ما تنام',
      description: 'Leverage sleep consolidation for memory.',
      descriptionAr: 'النوم هيثبت المعلومات دي في دماغك.',
      duration: '10m',
    },
    {
      icon: 'ban-outline',
      title: 'No excuses day',
      titleAr: 'يوم من غير أعذار',
      description: 'Commit to executing today despite obstacles.',
      descriptionAr: 'اوعد نفسك إنك هتخلص مهما كانت الظروف.',
      duration: '1d',
    },
  ],
  'discipline+health': [
    {
      icon: 'walk-outline',
      title: 'Exercise even when tired',
      titleAr: 'اتمرن حتى لو مكسل',
      description: 'Discipline is doing it when you don\'t feel like it.',
      descriptionAr: 'الانضباط هو إنك تعمل الحاجة وأنت مش عايز.',
      duration: '30m',
    },
    {
      icon: 'restaurant-outline',
      title: 'No junk food today',
      titleAr: 'مفيش أكل جاهز النهاردة',
      description: 'Rule-based eating builds self-command.',
      descriptionAr: 'التحكم في أكلك بيبني قوة إرادتك.',
      duration: '1d',
    },
    {
      icon: 'bed-outline',
      title: 'Sleep and wake on time',
      titleAr: 'نام واصحى في ميعادك',
      description: 'The foundation of daily physical discipline.',
      descriptionAr: 'ده أساس الانضباط الجسماني لأي حد.',
      duration: '8h',
    },
  ],
  'discipline+life_balance': [
    {
      icon: 'calendar-outline',
      title: 'Plan your whole day',
      titleAr: 'خطط ليومك كله',
      description: 'Decide in advance how you spend time.',
      descriptionAr: 'قرر من بدري وقتك هيضيع في إيه.',
      duration: '15m',
    },
    {
      icon: 'sparkles-outline',
      title: 'Make your bed',
      titleAr: 'رتب سريرك',
      description: 'Win the first struggle of the day instantly.',
      descriptionAr: 'اكسب أول معركة ليك في اليوم بمجرد ما تصحى.',
      duration: '3m',
    },
    {
      icon: 'phone-portrait-outline',
      title: 'Screen time under 3 hours',
      titleAr: 'وقت الشاشة أقل من ٣ ساعات',
      description: 'Strict limit on entertainment applications.',
      descriptionAr: 'حط ليمت صارم على تطبيقات الترفيه اللي بتسحب الوقت.',
      duration: '3h',
    },
  ],
  'consistency+work': [
    {
      icon: 'list-outline',
      title: 'Show up and do 1 task',
      titleAr: 'افتح اللاب وخلص مهمة واحدة',
      description: 'Minimum execution keeps consistency chain alive.',
      descriptionAr: 'عشان تحافظ على سلسلة استمراريتك شغالة.',
      duration: '15m',
    },
    {
      icon: 'checkmark-circle-outline',
      title: 'End day with review',
      titleAr: 'أنهي اليوم بمراجعة للي عملته',
      description: 'Reflect on wins to reinforce tomorrow\'s cycle.',
      descriptionAr: 'افتكر إنجازاتك عشان تبدأ بكرة بقوة.',
      duration: '10m',
    },
    {
      icon: 'refresh-outline',
      title: 'Repeat yesterday\'s win',
      titleAr: 'كرر إنجاز امبارح',
      description: 'Stack consecutive days for compounding success.',
      descriptionAr: 'تراكم الأيام الناجحة هيوصلك لنتائج مضاعفة.',
      duration: '30m',
    },
  ],
  'consistency+study': [
    {
      icon: 'book-outline',
      title: 'Study at least 15 min',
      titleAr: 'ذاكر ١٥ دقيقة على الأقل',
      description: 'Small daily studies beat cramming sessions.',
      descriptionAr: 'قليل دائم خير من حشو وقت الزنقة.',
      duration: '15m',
    },
    {
      icon: 'pencil-outline',
      title: 'Write one learning',
      titleAr: 'اكتب فايدة واحدة اتعلمتها',
      description: 'Documenting wins turns memory into habit.',
      descriptionAr: 'كتابة اللي اتعلمته بتحول الذاكرة لعادة يومية.',
      duration: '5m',
    },
    {
      icon: 'refresh-outline',
      title: 'Don\'t break the chain',
      titleAr: 'ماتقطعش السلسلة',
      description: 'Never miss two days in a row.',
      descriptionAr: 'إياك تفوت يومين ورا بعض.',
      duration: '15m',
    },
  ],
  'consistency+health': [
    {
      icon: 'walk-outline',
      title: 'Move your body 15 min',
      titleAr: 'حرك جسمك ١٥ دقيقة',
      description: 'Consistency of exercise beats intensity over time.',
      descriptionAr: 'الاستمرارية في التمرين أهم من شدته.',
      duration: '15m',
    },
    {
      icon: 'water-outline',
      title: 'Drink water consistently',
      titleAr: 'اشرب ماية بانتظام',
      description: 'Spread hydration throughout your morning.',
      descriptionAr: 'وزع شرب الماية على مدار اليوم.',
      duration: '5m',
    },
    {
      icon: 'bed-outline',
      title: 'Same sleep time',
      titleAr: 'نام في نفس الوقت',
      description: 'Aligning body clock makes waking effortless.',
      descriptionAr: 'تظبيط ساعة الجسم بيخلي الصحيان سهل جداً.',
      duration: '8h',
    },
  ],
  'consistency+life_balance': [
    {
      icon: 'partly-sunny-outline',
      title: 'Morning routine 10 min',
      titleAr: 'روتين الصبح ١٠ دقايق',
      description: 'A stable morning routine anchors the entire day.',
      descriptionAr: 'روتين الصبح هو اللي بيظبط بقية يومك.',
      duration: '10m',
    },
    {
      icon: 'phone-portrait-outline',
      title: 'Digital detox 1 hour',
      titleAr: 'افصل عن الديجيتال ساعة',
      description: 'Give your mind a daily tech rest period.',
      descriptionAr: 'إدي عقلك راحة يومية من الشاشات.',
      duration: '1h',
    },
    {
      icon: 'body-outline',
      title: 'End day with gratitude',
      titleAr: 'اختم يومك بالامتنان',
      description: 'Write down 3 things that went well today.',
      descriptionAr: 'اكتب ٣ حاجات حلوة حصلتلك النهاردة.',
      duration: '5m',
    },
  ],
};

const FALLBACK: Omit<Action, 'id' | 'completed'>[] = [
  {
    icon: 'locate-outline',
    title: 'Complete one important task',
    titleAr: 'خلص مهمة واحدة مهمة',
    description: 'Break procrastination by finishing one single priority.',
    descriptionAr: 'اكسر الكسل بإنك تخلص أولوية واحدة بس.',
    duration: '30m',
  },
  {
    icon: 'phone-portrait-outline',
    title: '1 hour without phone',
    titleAr: 'ساعة من غير موبايل',
    description: 'Keep your phone out of sight for absolute focus.',
    descriptionAr: 'ابعد موبايلك عن عينك عشان تركز بجد.',
    duration: '1h',
  },
  {
    icon: 'walk-outline',
    title: '15 min physical activity',
    titleAr: '١٥ دقيقة حركة',
    description: 'Get moving to lift energy and focus.',
    descriptionAr: 'اتحرك عشان ترفع طاقتك وتفوق.',
    duration: '15m',
  },
];

export function generatePlan(struggle: Struggle | null, goal: Goal | null): Action[] {
  const key = `${struggle ?? 'procrastination'}+${goal ?? 'work'}`;
  const templates = ACTION_BANK[key] ?? FALLBACK;

  return templates.map((t, i) => ({
    ...t,
    id: `action_${Date.now()}_${i}`,
    completed: false,
  }));
}
